language: node_js
node_js:
  - 10

services:
  - docker

before_install:
  - docker build -t docker-test:latest .
  - docker images

after_success:
- ./docker_push.sh

deploy:
  provider: heroku
  api_key:
    secure: "$HEROKU_API_KEY"
  app: dockerize-testing
 
