language: node_js
node_js:
- 10
services:
- docker
before_install:
- docker build -t docker-test:latest .
- docker images

after_success:
  - docker login $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export REPO=htotheo/docker-test
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
  - docker build -f Dockerfile -t $REPO:$COMMIT .
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO

deploy:
  provider: heroku
  api_key:
    secure: fUEWs1XKAJTMbNgkrPuZdfONXxUWDOo3q2zgST18DAvAqIHoIOWNt/ryQTFZl6tNhU18smD7rZZOlHuqE3nT5W9bJcsrrn+xZ0yZV0f644Nk0tgalXu2UzHXPeDwZaTpO1Vo3bOuyw59Q/sAOmrXhfxOf4PBd0d2sdAW9q1TJR9g9zuHXKOj6weupy6BVln7fFsmTUTxbcr2uwq0D7pT7dEpnJdY6t2ZXtWU4hSkY1JL7TldUUcelFg+gr30eUxM3zBYtuYon5tfmo79dGyUywgfznYrvUOftQ8NHpZtN+9Dd4maLAH0swc6cQhEJi0viiiODhhlQNRAxHSAb+srxHCt28PxQ9M4ZD42KqI/QHT5qLICrH7aZutN1HL0m7Swt2MU1w8MYOD64xe2KN9LbAeBP8VY2P72iv1xcGWnjb0qj62jvaw2tKcB60n1t9QYiROyAdaAYds+6iMpCcNeeYQFOBc5aaLjzIuY9lRZZDBrBabhT5IoeM+42BF3hcXk+TAhNeQin3SrseMqpULABPOX8fWVeDGvxZTIuGH0JnHuDCfB7m7qrToGK9cMj33UCq4j28IU6JJYLUFq/GEhfTGmwqjvyXJPDy2uHo2S7iIy+UVVrDzEwAFO/KrzjQQz93SzFViJ6pOljll/Y2FtKYMjU7wN6DoDFGofirlo7tg=
  app: dockerize-testing
env:
  global:
  - secure: GhXFqW0ZbvTqdvBxphEdwtwuQ2eW3ROyUvRj4ADxmdnKwplG1S5kwd0YPsKQMU1z5ScomUtDL1W2HT3qnm1beaUdll5e35UKre5xgapwbEypR4O3AaEuYd5Mg0l9GJ8gEwpvgCP6B/qfWxTo2+tTSEtgpR16k5vGIkmZ9I12BWaKyYVc5gJYjFRVAvP0ix3VCBtGEZDsdEKROXvZDSRVVf/7CfAulgQEHoXmi02tYIy8LP+L65UcuBg6pIvOjyU678le6mZ80u8R/KLYdBqtFVTBhnz3lRoXDBGZPaWqhN3/m1pwz/cwQ7QIePjQSPuhqCzt242l49BM2CLmgdcryMqbtNHVHsBwj4mUC3JEVRjwIJDYC/e4UTIfC09nRzGFkYszgTDkn781APJ+/AoFy8rX3cxuC/fRJdfjgJD869RtxVnL733qPLdxJk9Sax9gxtyUmDtMpHIGTx/mxRUj56IFMeGhBy8uxr/2tc9KSwKwWy5vQ8Yews1Kuh6CAnpCtaCv5O5Z0IPOBKmKF+56pO9UHhadRCjgbqDxoyVI59enE+Mpzrt6K2M18EV901LcP7J9sR/ufIvmB+NRugLl6ZulIBvBtth6Jp8cDZnePde++rtoo8hRKbM7ZElSvhNrO5QZQ8tgz7AtuWKDxs8iO+opcMWo+3S6+n27/j7F2iY=
  - secure: IQG2b+Hqxl+rgHtg91knDcuhZ5Z/TLDhWcTN/1Agno8unmQKUzRojML7hu/NlQpebGU2+dItB1gCoWXj2bNIJbfLPUwP78XXjWPF9HyDYz3j64tAXt25cyC1kAI8DijZNiiTwga6h1fkKmYtIsdm/Yn2yB3GM650pUXrtxoGhW7sfDi7rsCzi3bnSak/n/8oGM/Vfxe8rbcfG3p/L9HssLTOom2Kmg6hwsT1Kg2CBBs3B6BicpDZ2WKFok4mENr3VlbMDe3lzNlDc7T8sAEVlOFfWDNJ5KJdf/orJVjDlmRrvbjqVN4nS8upTespVZhUmOD66lov4AiQ6gv/meqdJRy1fTHId4gj3T8rOcC3mDY6j8UGYoOCtujjdN3cI5aXhUbdTk8VdnbBdUOTyZPrvg7IOk+fJyyyoCeIakT1ildNJ9fbLW6SCyv3vRTY9UoFhsNE98HLPvAUT1E7Qv5vFq3fr0a2EKgahVwf+r25Qx9lGn5iB1SdETZ4/lVgD6mVC+ArA0aXHX/aRtyIkbyXAnvlaSFevtoZPr2rLYonSVEYSw6HTbKJnXc2/CaOikopYRTyLyTasEKjMVq11L1ZYA2V37R0th8l2tKb006EpKIIJAGhS8c8G2r8rYCC5SAxfe2l1Iv+EvBNdrPudqStGF8z21tpcNk3gqxoPJXkFXc=
  - secure: hFGHlLhbRYkUcx9xytGX7rHgr+QkW5tQPthjRnolOnJgPKBaD5jdF6WcZDPpX8oZr0iyYOjweB4T9sarxwjTB1RDwehAZcWwYWcv3Z4uatWSxZ2cIKkEB+GpO+aRAHJk2DTMBmcRQPUSdEDhbG2IFiYzReYhWqWGgeYSVOKbLSK0ZcKITzAT2h5KXtCDtVUkVllE6OXBFgYlf47BTtqrKsi2BETg39yD6ByFzqptgWzjnX6lcxh5+QId2N6jiyN6FAWFbD7zUGICT4cpFGk7lnHBbkOem3we4TS/ihCOaxdBPacKaEz5VG8rqli/1z/J65ctxv+WdtQ1gBY+ViT5BAB1imOpZnk/fyh2qSGGrcwxo8a4iUC9rCwEMqbVCZ1VXSjzAJiflf+ZR4b7qaG7WU/jiYLuxpRi0inxrPOSZHAydo5LCRxgtw/NVRCnsrqpx6FMLiy1a6y7sF1OeJ+0VNEHTgzgVGhGI9CtKSJiiY6b28XdhEenYBhOYwtCeuE4TgBOn9cJ3PPSdfijgLq4CLuHaTrEpG1ow2eJiSPyFBoc2m/zA+pFTdNZGhskh+SacXJgv2wWH6iQ2VXk7+9PU6lalaHl4mDA/x3JRNKuSYbK70QWV8ScNsFZzeFW+MKcUeQlvfznWRHth562oI+Al8jLiAU1Bt92gTFfsUuYZNg=
  - COMMIT=${TRAVIS_COMMIT::8}