language: node_js
node_js:
  - 10

services:
  - docker

before_install:
  - docker build -t docker-test:latest .
  - docker images

after_success:
  provider: script
  script: bash docker_push
  on:
    branch: master

deploy:
  provider: heroku
  api-key:
    secure: "$HEROKU_API_KEY"
  app: dockerize-testing
  on:
    tags: true
    repo: video-hooks
